ARG IMAGE_REGISTRY=IMAGE_REGISTRY
FROM ${IMAGE_REGISTRY}/airflow:2.4.3-python3.7-slim-base-v1
ARG IMAGE_TYPE=IMAGE_TYPE
USER root
COPY ${IMAGE_TYPE}-apt-pkgs.txt .

RUN apt-get update \
  && xargs apt-get install -y <${IMAGE_TYPE}-apt-pkgs.txt \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
