name: 'airflow cust image build'
on:
  workflow_dispatch:
  push:
    branches:
      - "image-build/**"
  workflow_run:
    workflows: ["airflow base image build"]
    types: 
      - completed

env:
  BASE_IMAGE_REGISTRY: coolcool97

jobs:
  Generate_Image_Tag:
    runs-on: ubuntu-latest
    outputs:
      image_list: ${{ steps.set-image-tag-matrix.outputs.image_list }}
    steps:
      - uses: actions/checkout@v3
      - name: Read Image Tag List
        id: set-image-tag-matrix
        working-directory: cust
        run: |
          echo "image_list=$(cat image_list.txt)" >> $GITHUB_OUTPUT
          echo "image_list=$(cat image_list.txt)" >> $GITHUB_ENV
      - run: |
          echo "image_list: $image_list"
          
  Image_Build_Push:
    needs: Generate_Image_Tag
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        image_tag: ${{fromJSON(needs.Generate_Image_Tag.outputs.image_list)}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate ${{ matrix.image_tag }} Image Variables
        run: |
          ls
          echo "image tag: ${{ matrix.image_tag }}"
          strarr=($(echo "${{ matrix.image_tag }}" | sed 's/-/ /g'))
          len=$((${#strarr[*]}-3))
          sep_arr=${strarr[*]:2:len}
          image_type=$(echo "$sep_arr" | sed 's/ /-/g')
          echo "image_type=$image_type" >> $GITHUB_ENV
          echo "dockerfile=Dockerfile.$image_type" >> $GITHUB_ENV 
          echo "image tag: ${{ matrix.image_tag }}"
      - run: |
          echo "dockerfile name: $dockerfile"
          echo "image_type: $image_type"

      - name: ${{ matrix.image_tag }} Image Build
        working-directory: cust
        run: |
          export BUILDKIT_PROGRESS=plain
          docker build . -f "$dockerfile" -t "$IMAGE_REGISTRY"/"airflow:${{ matrix.image_tag }}" \
          --build-arg BASE_IMAGE_REGISTRY="$BASE_IMAGE_REGISTRY" \
          --build-arg IMAGE_TYPE="$image_type"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_REGISTRY }}/airflow:${{ matrix.image_tag }}
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: ${{ matrix.image_tag }} Image Push
        working-directory: base
        run: |
          docker push "$IMAGE_REGISTRY"/"airflow:${{ matrix.image_tag }}"
