name: 'github action for airflow image build'
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    types:
      - closed
jobs:
  image_processing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Image Build
      run: |
        ls
        docker build airflow-service -t coolcool97/airflow:2.4.3-python3.7
        docker build airflow-worker -t coolcool97/airflow:slim-2.4.3-python3.7

    - uses: docker/login-action@v2
    - name: Login to Docker Hub
      with:
      - username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Image Push
      run: |
        docker push coolcool97/airflow:2.4.3-python3.7
        docker push coolcool97/airflow:slim-2.4.3-python3.7