name: 'github action for airflow image build'
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    types:
      - closed

env:
  IMAGE_REGISTRY: coolcool97/airflow
  AIRFLOW_IMAGE_TAG: 2.4.3-python3.7
  AIRFLOW_WORKER_IMAGE_TAG: slim-2.4.3-python3.7

jobs:
  image_processing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Image Build
        run: |
          ls
          docker build . -t $IMAGE_REGISTRY:$AIRFLOW_IMAGE_TAG --build-arg AIRFLOW_IMAGE_TAG=$AIRFLOW_IMAGE_TAG
          docker build . -t $IMAGE_REGISTRY:$AIRFLOW_WORKER_IMAGE_TAG --build-arg AIRFLOW_IMAGE_TAG=$AIRFLOW_WORKER_IMAGE_TAG

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image Push
        run: |
          docker push $IMAGE_REGISTRY:$AIRFLOW_IMAGE_TAG
          docker push $IMAGE_REGISTRY:$AIRFLOW_WORKER_IMAGE_TAG
