name: 'github action for airflow image build'
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    types:
      - closed
jobs:
  image_processing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Image Build
      run: |
        docker build -f airflow-service/Dockerfile -t coolcool97/airflow:2.4.3-python3.7
        docker build -f airflow-service/Dockerfile -t coolcool97/airflow:slim-2.4.3-python3.7